Add warning/error messages on login screen
usdigitalresponse/arpa-reporter pull request #521
Opened 2022-09-13 19:30 UTC by trumanc

This PR adds a couple simple error/warning alerts that are configurable via env variable.
It supports a warning message that still allows the user to login (in case they want to sign in and access their old data/reports, as well as an error version that blocks the login process entirely.

The messages themself are set in the env variable, so we can include useful info like the url for the new tool, and reminders to update their bookmarks, etc...

If login is fully disabled:
<img width="985" alt="Screen Shot 2022-09-13 at 12 23 51 PM" src="https://user-images.githubusercontent.com/3675290/189992320-2c540405-e612-4b6b-82d3-52f6d54dcf69.png">

If it's only a warning message:
<img width="975" alt="Screen Shot 2022-09-13 at 12 22 50 PM" src="https://user-images.githubusercontent.com/3675290/189992326-5f6ac919-0f71-42d0-8c2b-4204c6221dd3.png">

2022-09-14 05:16 UTC, ajhyndman requested changes

2022-09-14 05:16 UTC, ajhyndman commented on src/server/routes/sessions.js
> +    })
```suggestion
    return res.json({
      success: false,
      message: `Login disabled: ${LOGIN_DISABLED_MESSAGE}`
    })
```

I assume you mean to actually prevent sending the email in this case?  In which case, this line should return.

2022-09-14 05:16 UTC, ajhyndman commented
Thanks for putting this together!

2022-09-15 00:40 UTC, mattbroussard commented
One thought is it would be nice for the URL to be a clickable link. Could either use something like [this](https://www.npmjs.com/package/linkifyjs) to linkify via regex, make the env variable be HTML, or change the structure of the message so the text and URL are in separate variables.

2022-09-15 01:04 UTC, trumanc commented
@mattbroussard  I considered making the link clickable, but decided against it for a couple minor reasons:
First: I wasn't thrilled with any if the implementation options (installing a new dependency for a temporary feature seems like overkill, raw html seems error prone, as does making the message and url separate env variables that could be sent separately.

Second: I'm actually not mad about the user having to copy/paste the link, because if they're seeing this message it probably means that they followed an out-of-date bookmark that they should edit anyways. The more painful this 'follow-the-link' process is, the more likely they are to update the bookmark and not make the mistake again in the future.

If you feel strongly about making it clickable I can definitely add it though! Just let me know

2022-09-20 16:17 UTC, ajhyndman approved these changes

2022-09-22 16:03 UTC, merged